title:            WedgieEdward
description:      Edward Thomason's Personal Page
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://wedgieedward.github.io
disqus_shortname:

# Owner/author information
owner:
  name:           Edward Thomason
  avatar:         bio-photo.jpg
  bio:            "Python Developer. Alt Rock Fan. I press buttons and hope i don't break the world."
  email:          your@email.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: wedgieedward
  facebook: wedgieedward
  github: wedgieedward
  stackoverflow: wedgieedward
  linkedin:
  instagram: wedgieedward
  lastfm: wedgieedward
  tumblr:
  pinterest:
  foursquare:
  steam: wedgieedward
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: TrackerDash
    url: /TrackerDash/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
